---
title: "Pickem Charts"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Loading_packages, message=FALSE}
library(tidyverse)
library(moderndive)
library(janitor)
library(corrr)
```

```{r Reading_Files, message=FALSE, warning=FALSE}
Pickem <- read_csv(here::here("2021- Pickem League Wins.csv")) %>% 
  clean_names()


```

```{r Comparison of Chris Vs Jake}
Chris <- Pickem %>% 
  summarise(chris,week)
Jake <- Pickem %>% 
  summarise(jake,week)

ggplot() + geom_point(data=Chris,aes(x=chris, y=week), colour='red') + geom_point(alpha=.5) + geom_point(data=Jake, aes(x=jake, y=week), colour= 'blue') + geom_point(alpha=.5)

```


```{r Mean of Each week}
 Mean_WK <-Pickem %>% 
 rowwise() %>% 
  mutate(m=mean(c_across(2:12))) %>% 
  ungroup() %>% 
  summarise(m)
Mean_WK
```



```{r Bohr vs Stase}
jack <- Pickem %>% 
  summarise(jack,week)
matt <- Pickem %>% 
  summarise(matt,week)

BvM <- ggplot() + geom_point(data=jack,aes(x=jack, y=week), colour='red') + geom_point(alpha=.5) + geom_point(data=matt, aes(x=matt, y=week), colour= 'blue') + geom_point(alpha=.5)

BvM + scale_x_continuous(name="Bohr Vs Stase", breaks =c(0:16))

```


```{r Correlations between the mean and users}

 Corr_Mn <-Pickem %>% 
 rowwise() %>% 
  mutate(m=mean(c_across(2:12))) %>% select(2:13) %>% 
    correlate()
Corr_Mn



```







